[workspace]
members = [
]

[package]
name = "xzoom"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[dependencies]
libc = "0.2"

[[bin]]
name = "xzoom"
path = "src/main.rs"
