CLIPPY_CATEGORY_MAP = {
    "Dead Code": [
        "unused",
        "never used",
        "unreachable",
        "never read",
    ],
    "Undefined Behavior": [
        "panic",
        "undeclared",
    ],
    "Memory Safety": [
        "unwrap",
        "unsafe",
        "manual memory management",
        r"regex:0 as \*(const|mut)",
    ],
    "Null Pointer Dereference": [
        "null",
    ],
    "Type Safety": [
        "casting",
        "borrowed",
        "reference",
        "extern types are experimental",
        "lossy conversion",
    ],
    "Memory Leaks": [
        "leak",
    ],
    "Arithmetic Issues": [
        "integer overflow",
        "operator precedence",
    ],
    "Redundant Operations": [
        "redundant",
       "unnecessary operation",
       "called `expect` on",
    ],
    "Security/Insecure APIs": [
        "security",
    ],
    "Code Smells": [
        "crate-level attribute",
        "can be collapsed",
        "unnecessary double parentheses",
        "unnecessary parentheses",
        "branch is empty",
        "regex:should have (an|a) [a-z ]+ case name",
        "variable does not need to be mutable",
        "statement with no effect",
        "trying to use `match` for an equality check",
        "manual implementation",
        "this boolean expression can be simplified",
        "unneeded `return` statement",
        "contains a capitalized acronym", 
        "wildcard pattern covers any other pattern",
        "can be rewritten with",
        "excessive precision",
        "module has the same name",
        "more descriptive name",
        "returning the result of a `let` binding from a block",
        r"regex:^manual.*implementation$",
        r"regex:swapping [`'\"]?\*?[a-zA-Z_]+[`'\"]? and [`'\"]?\*?[a-zA-Z_]+[`'\"]? manually"
    ],
    "Build Configuration Error": [
        "#![feature]",
        "linkage",
        "function not found in crate",
        "has been stable",
        "inner attribute",
        "unresolved import",
        "cannot find function",
        "c-variadic functions are unstable",
        "use of unstable library feature",
        "redeclared with a different signature",
    ],
}
